import { defineToolcraft } from "@/toolcraft/runtime";

export const allowedPalette = [
  "#C2FE0C",
  "#EA027E",
  "#3601FB",
  "#FF5500",
  "#01FFFF",
  "#29324F",
  "#EA0049",
  "#0E111B",
  "#2BDBC8",
  "#ECEB14",
  "#DFFF00",
] as const;

const paletteOptions = allowedPalette.map((color) => ({
  label: color,
  value: color,
}));

export const appSchema = defineToolcraft({
  canvas: {
    draggable: true,
    enabled: true,
    sizing: { mode: "editable-output" },
    size: { height: 2000, unit: "px", width: 1600 },
    upload: true,
  },
  export: {
    png: {
      background: "include",
    },
  },
  panels: {
    controls: {
      sections: [
        {
          title: "Libraries",
          controls: {
            useMainLibrary: {
              defaultValue: true,
              description: "Use the recovered main micrographics folder.",
              label: "Main library",
              performanceReason: "Toggling the main library selects a fixed built-in symbol pool.",
              performanceRole: "responsiveness",
              target: "source.useMainLibrary",
              type: "switch",
            },
            useStaveLibrary: {
              defaultValue: true,
              description: "Use the STAVE micrographics folder.",
              label: "STAVE library",
              performanceReason: "Toggling the STAVE library selects a fixed built-in symbol pool.",
              performanceRole: "responsiveness",
              target: "source.useStaveLibrary",
              type: "switch",
            },
          },
        },
        {
          title: "Source",
          controls: {
            svgFiles: {
              accept: ".svg,image/svg+xml",
              assetKind: "file",
              defaultValue: [],
              description: "Drop one or more SVG files to mix with the micrographics library.",
              label: "SVG files",
              multiple: true,
              performanceReason: "More uploaded symbols increase decoded SVG count and placement variety.",
              performanceRole: "workload",
              target: "source.svgFiles",
              type: "fileDrop",
            },
            maskImage: {
              accept: "image/*",
              assetKind: "image",
              defaultValue: [],
              description: "Optional image used as a brightness map for grid placement.",
              label: "Image mask",
              multiple: false,
              performanceReason: "Uploaded mask images are sampled into the placement grid.",
              performanceRole: "workload",
              target: "source.maskImage",
              type: "fileDrop",
            },
            svgText: {
              defaultValue: "",
              description: "Optional raw SVG markup. Separate multiple SVGs with blank lines.",
              label: "Pasted SVGs",
              performanceReason: "Long pasted SVG markup changes symbol parsing and preview output.",
              performanceRole: "workload",
              target: "source.svgText",
              type: "code",
            },
            words: {
              defaultValue: "STAVE\nCHORD_TICKER\nBEAT_SYNC\nAUDIO_WINDOW\nRING_BUFFER\nSIDECAR\nMADMOM\nVITERBI\nCRF\nPCM_STREAM\nWAVEFORM\nLOOPBACK\nCAPTURE\nSTART\nSTOP\nLISTENING\nLATENCY\nSHM_LATER",
              description: "Words are placed on the same invisible grid as SVG symbols.",
              label: "Words",
              performanceReason: "Longer word lists add text candidates to the seeded layout.",
              performanceRole: "workload",
              target: "source.words",
              type: "code",
            },
          },
        },
        {
          title: "Grid",
          controls: {
            seed: {
              commitMode: "content",
              defaultValue: "ARCHIVE-2026",
              description: "Same seed always creates the same layout.",
              label: "Seed",
              performanceReason: "Seed changes reorder the deterministic grid but do not alter workload size.",
              performanceRole: "responsiveness",
              target: "grid.seed",
              type: "text",
            },
            columns: {
              defaultValue: 18,
              label: "Columns",
              markerCount: 5,
              max: 32,
              min: 6,
              performanceReason: "Higher column counts increase grid cells and rendered placements.",
              performanceRole: "workload",
              step: 1,
              target: "grid.columns",
              type: "slider",
            },
            rows: {
              defaultValue: 22,
              label: "Rows",
              markerCount: 5,
              max: 40,
              min: 6,
              performanceReason: "Higher row counts increase grid cells and rendered placements.",
              performanceRole: "workload",
              step: 1,
              target: "grid.rows",
              type: "slider",
            },
            scale: {
              defaultValue: 0.82,
              label: "Grid scale",
              markerCount: 5,
              max: 1.5,
              min: 0.35,
              performanceReason: "Scale changes geometry size without changing item count.",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "grid.scale",
              type: "slider",
            },
            jitter: {
              defaultValue: 12,
              label: "Jitter",
              markerCount: 5,
              max: 40,
              min: 0,
              performanceReason: "Jitter changes per-item offsets without changing workload size.",
              performanceRole: "responsiveness",
              step: 1,
              target: "grid.jitter",
              type: "slider",
              unit: "%",
            },
            density: {
              defaultValue: 58,
              label: "Density",
              markerCount: 5,
              max: 100,
              min: 5,
              performanceReason: "Density controls how many grid cells receive symbols.",
              performanceRole: "workload",
              step: 1,
              target: "grid.density",
              type: "slider",
              unit: "%",
            },
            maskMode: {
              defaultValue: "none",
              label: "Image mask",
              options: [
                { label: "Off", value: "none" },
                { label: "Light areas", value: "light" },
                { label: "Dark areas", value: "dark" },
              ],
              performanceReason: "Image mask mode changes grid placement probability after the mask is sampled.",
              performanceRole: "workload",
              target: "grid.maskMode",
              type: "select",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["columns", "rows"], layout: "inline" },
          ],
        },
        {
          title: "Spans",
          controls: {
            spanChance: {
              defaultValue: 24,
              label: "Chance",
              markerCount: 5,
              max: 80,
              min: 0,
              performanceReason: "Span chance changes item dimensions and overlap complexity.",
              performanceRole: "responsiveness",
              step: 1,
              target: "span.chance",
              type: "slider",
              unit: "%",
            },
            maxSpan: {
              defaultValue: 3,
              label: "Max span",
              markerCount: 3,
              max: 5,
              min: 1,
              performanceReason: "Larger spans increase individual SVG/text bounds.",
              performanceRole: "responsiveness",
              step: 1,
              target: "span.max",
              type: "slider",
            },
            wordChance: {
              defaultValue: 18,
              label: "Words",
              markerCount: 5,
              max: 70,
              min: 0,
              performanceReason: "Word chance changes text placement count in the vector renderer.",
              performanceRole: "workload",
              step: 1,
              target: "span.wordChance",
              type: "slider",
              unit: "%",
            },
            rotate: {
              defaultValue: 10,
              label: "Rotate",
              markerCount: 5,
              max: 45,
              min: 0,
              performanceReason: "Rotation changes transforms without changing output count.",
              performanceRole: "responsiveness",
              step: 1,
              target: "span.rotate",
              type: "slider",
              unit: "°",
            },
          },
        },
        {
          title: "Palette",
          controls: {
            backgroundColor: {
              defaultValue: "#0E111B",
              label: "Background",
              options: paletteOptions,
              performanceReason: "Background color is a lightweight paint update.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "select",
            },
            foregroundColor: {
              defaultValue: "#C2FE0C",
              label: "Graphics",
              options: paletteOptions,
              performanceReason: "Graphic color is a lightweight paint update.",
              performanceRole: "responsiveness",
              target: "appearance.foreground",
              type: "select",
            },
            accentColor: {
              defaultValue: "#01FFFF",
              label: "Accent",
              options: paletteOptions,
              performanceReason: "Accent color is a lightweight paint update.",
              performanceRole: "responsiveness",
              target: "appearance.accent",
              type: "select",
            },
            grain: {
              defaultValue: 18,
              label: "Grain",
              markerCount: 5,
              max: 60,
              min: 0,
              performanceReason: "Grain changes a single SVG filter opacity.",
              performanceRole: "responsiveness",
              step: 1,
              target: "appearance.grain",
              type: "slider",
              unit: "%",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["backgroundColor", "foregroundColor"],
              layout: "inline",
            },
          ],
        },
        {
          title: "Background",
          controls: {
            includeBackground: {
              defaultValue: true,
              label: "Include",
              performanceReason: "Background include toggles preview/export compositing.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            exportBackground: {
              defaultValue: { hex: "#0E111B" },
              label: false,
              performanceReason: "Export background color is a lightweight paint update.",
              performanceRole: "responsiveness",
              target: "export.background",
              type: "color",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["includeBackground", "exportBackground"],
              layout: "inline",
            },
          ],
        },
        {
          title: "Image Export",
          controls: {
            imageFormat: {
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceReason: "Format selection is lightweight; PNG is exported first and JPG is reserved for follow-up.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason: "Higher export resolutions increase PNG rasterization work.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["imageFormat", "imageResolution"],
              layout: "inline",
            },
          ],
        },
        {
          title: "Output",
          controls: {
            actions: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  value: "export-png",
                },
              ],
              defaultValue: "",
              label: "Export",
              target: "output.actions",
              type: "panelActions",
              variant: "primary",
            },
          },
        },
      ],
      title: "Micrographics",
    },
  },
  persistence: {
    include: ["values", "canvas", "panels", "media"],
    key: "toolcraft:micrographics-grid:state:v1",
    storage: "localStorage",
    version: 1,
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
