import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: ["parse-symbols", "build-layout", "svg-preview"],
        targets: ["source.svgText", "source.words", "grid.seed", "grid.columns", "grid.rows"],
      },
      {
        interaction: "control-drag",
        invalidates: ["build-layout", "svg-preview"],
        targets: ["grid.density", "grid.scale", "grid.jitter", "span.chance", "span.max"],
      },
      {
        interaction: "export",
        invalidates: ["canvas-export"],
        targets: ["export.image.resolution", "export.includeBackground", "export.background"],
      },
    ],
    passes: [
      {
        cacheKey: ["source.svgText", "mediaAssets"],
        id: "parse-symbols",
        inputs: ["starter symbols", "pasted SVGs", "uploaded SVGs"],
        invalidatedBy: ["source.svgText", "source.svgFiles"],
        kind: "preprocess",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["grid.*", "span.*", "source.words", "symbol count"],
        id: "build-layout",
        inputs: ["runtime values", "symbols", "words"],
        invalidatedBy: ["grid.*", "span.*", "source.words", "source.svgText", "source.svgFiles"],
        kind: "vector-build",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
      {
        id: "svg-preview",
        inputs: ["layout"],
        invalidatedBy: ["layout", "appearance.*", "export.includeBackground"],
        kind: "composite",
        output: "preview",
        quality: "retina",
        runsOn: "main",
      },
      {
        id: "canvas-export",
        inputs: ["layout", "appearance", "export settings"],
        invalidatedBy: ["export.image.resolution", "layout", "appearance.*"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "svg",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Uploaded SVGs render exactly in preview through SVG image embedding; PNG export uses a canvas-safe symbolic fallback for uploaded artwork.",
    ],
    layers: [
      {
        content: ["geometry", "text", "dense-pattern"],
        exportMode: "included",
        id: "micrographics-grid",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "svg",
        uiSelector: "[data-testid='micrographics-output']",
      },
    ],
    performanceRisks: [
      "Very high row, column, density, and pasted SVG values can create hundreds of SVG nodes.",
    ],
    previewExportDifferenceReason:
      "Preview keeps SVG/vector fidelity; export uses Canvas 2D through the Toolcraft PNG helper to guarantee PNG bytes and selected resolution.",
    previewRenderer: "svg",
    productRepresentation: "mixed",
    rendererStrategy: "svg",
    rendererWorkload: "vector-output",
    sourceRepresentation: "mixed",
    whyNotAlternativeStrategies: [
      "DOM would make export and SVG symbol transforms harder to keep aligned to the grid.",
      "WebGL/WebGPU are unnecessary for the current vector-count target and would rasterize semantic text too early.",
    ],
  },
  rendererWorkload: "vector-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "micrographics density updates product output",
      browser: true,
      browserTestName: "browser renders dense seeded micrographics without viewport shift",
      budget: { maxInteractionMs: 2000, maxPreviewMs: 2000 },
      expectedObservable: "Changing density changes the number of grid-aligned SVG/text marks.",
      fixture: "Seed ARCHIVE-2026 with dense grid settings.",
      id: "micrographics.density",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 86,
          smoothTargetRatio: 0.86,
          target: "grid.density",
          userFacingRange: "experimental-above-smooth",
        },
        reason: "Density is the primary item-count control.",
        value: 86,
      },
      target: "grid.density",
      values: { default: 58, max: 100, min: 5 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "micrographics export uses selected image resolution",
      browser: true,
      browserTestName: "browser exports PNG from seeded grid",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Export PNG produces a PNG from the current seeded grid.",
      fixture: "4K PNG export with default grid.",
      id: "micrographics.export",
      interaction: "export-copy",
      stressFixture: {
        kind: "max-value",
        reason: "8K is the heaviest exposed image export choice.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "source.svgFiles",
    "source.svgText",
    "source.words",
    "grid.columns",
    "grid.rows",
    "grid.density",
    "span.wordChance",
    "export.image.resolution",
  ],
});
